
import type { Memory, Photo, Reason, LoveQuote } from './types';

// The 'T00:00:00' part is important to avoid timezone issues and ensure the date is consistent.
export const START_DATING_DATE = new Date('2025-08-02T00:00:00');

export const INITIAL_MEMORIES: Memory[] = [
  {
    id: '1',
    date: new Date('2025-08-02T00:00:00'),
    title: 'Nossa Jornada Começou',
    description: 'O lindo dia em que oficialmente começamos a namorar e nossos corações se entrelaçaram.',
    tags: ['aniversário', 'amor'],
    image: 'https://i.pinimg.com/736x/81/71/51/8171515f162cc1254da32d59c23ad43f.jpg',
    dataAiHint: 'casal feliz',
  },
  {
    id: '2',
    date: new Date('2025-08-10T00:00:00'),
    title: 'Primeiro Encontro no Cinema',
    description: 'Assistimos aquela comédia romântica e não parávamos de rir. Lembra do incidente da pipoca?',
    tags: ['encontro', 'diversão'],
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'cinema casal',
  },
  {
    id: '3',
    date: new Date('2025-09-22T00:00:00'),
    title: 'Felicidade na Praia',
    description: 'Nossa primeira viagem à praia juntos. O pôr do sol era quase tão lindo quanto você.',
    tags: ['viagem', 'natureza'],
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'praia por do sol',
  },
   {
    id: '4',
    date: new Date('2025-10-15T00:00:00'),
    title: 'Passeio de Outono',
    description: 'Um dia tranquilo aproveitando o ar fresco e as cores do outono, sempre juntos.',
    tags: ['passeio', 'natureza'],
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'casal outono',
  },
  {
    id: '5',
    date: new Date('2025-11-05T00:00:00'),
    title: 'Abraço Aconchegante',
    description: 'Não há lugar no mundo onde eu me sinta mais seguro e amado do que em seus braços.',
    tags: ['carinho', 'amor'],
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'casal abraço',
  },
  {
    id: '6',
    date: new Date('2025-12-25T00:00:00'),
    title: 'Nosso Primeiro Natal',
    description: 'Celebrando o Natal juntos, criando nossas próprias tradições e memórias.',
    tags: ['celebração', 'feriado'],
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'casal natal',
  },
  {
    id: '7',
    date: new Date('2026-01-01T00:00:00'),
    title: 'Votos de Ano Novo',
    description: 'Brindando a um novo ano de amor, aventuras e felicidade um ao lado do outro.',
    tags: ['celebração', 'futuro'],
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'casal ano novo',
  },
];

export const INITIAL_PHOTOS: Photo[] = [
  {
    id: '1',
    src: 'https://placehold.co/521x927.png',
    alt: 'Um lindo abraço carinhoso',
    caption: 'Em seus braços, encontro meu porto seguro e todo o amor do mundo. ❤️',
    date: new Date('2025-11-05T00:00:00'),
    dataAiHint: 'casal abraço'
  },
  {
    id: '2',
    src: 'https://placehold.co/1647x927.png',
    alt: 'Celebrando um momento especial',
    caption: 'Cada momento com você se torna uma celebração da nossa felicidade.',
    date: new Date('2025-12-25T00:00:00'),
    dataAiHint: 'casal celebração'
  },
  {
    id: '3',
    src: 'https://placehold.co/1647x927.png',
    alt: 'Olhando para o futuro juntos',
    caption: 'Juntos, de mãos dadas, prontos para todos os lindos capítulos que ainda vamos escrever.',
    date: new Date('2026-01-01T00:00:00'),
    dataAiHint: 'casal futuro'
  },
  {
    id: '4',
    src: 'https://placehold.co/522x927.png',
    alt: 'Passeio tranquilo e romântico',
    caption: 'A simplicidade de um passeio se torna extraordinária quando estou com você.',
    date: new Date('2025-10-15T00:00:00'),
    dataAiHint: 'casal passeio'
  },
  {
    id: '5',
    src: 'https://placehold.co/522x927.png',
    alt: 'Explorando uma nova cidade',
    caption: 'Nossa aventura de fim de semana.',
    date: new Date('2025-11-18T00:00:00'),
    dataAiHint: 'casal viagem'
  },
];

export const INITIAL_REASONS: Reason[] = [
  { id: '1', text: 'Seu lindo sorriso que ilumina meu mundo inteiro todos os dias.' },
  { id: '2', text: 'Sua bondade e compaixão inabaláveis por todos que você conhece.' },
  { id: '3', text: 'A maneira como você me faz rir até a barriga doer, mesmo nos dias difíceis.' },
  { id: '4', text: 'Sua inteligência incrível e a forma como você vê o mundo.' },
  { id: '5', text: 'O quanto você apoia meus sonhos e ambições.' },
  { id: '6', text: 'Seu espírito aventureiro e disposição para experimentar coisas novas comigo.' },
  { id: '7', text: 'A forma como você sempre sabe como me confortar quando estou para baixo.' },
  { id: '8', text: 'Seu abraço, que é o meu lugar favorito no mundo.' },
  { id: '9', text: 'A paciência infinita que você tem comigo.' },
  { id: '10', text: 'O jeito que seus olhos brilham quando você fala sobre algo que ama.' },
  { id: '11', text: 'Você me inspira a ser uma pessoa melhor a cada dia.' },
  { id: '12', text: 'Sua lealdade e a certeza de que posso contar com você para tudo.' },
  { id: '13', text: 'A forma como transformamos momentos simples em memórias inesquecíveis.' },
  { id: '14', text: 'Sua força para enfrentar qualquer desafio que a vida apresenta.' },
  { id: '15', text: 'O som da sua risada é a minha melodia favorita.' },
  { id: '16', text: 'Porque você me entende com apenas um olhar.' },
  { id: '17', text: 'A maneira como você cuida de mim e se preocupa com meu bem-estar.' },
  { id: '18', text: 'Seu gosto musical incrível, que me apresentou tantas músicas novas.' },
  { id: '19', text: 'Você me faz sentir a pessoa mais amada e especial do universo.' },
  { id: '20', text: 'A segurança que sinto ao segurar sua mão.' },
  { id: '21', text: 'Sua paixão pela vida e por aprender coisas novas.' },
  { id: '22', text: 'Como você consegue ser a pessoa mais fofa e a mais forte ao mesmo tempo.' },
  { id: '23', text: 'As conversas profundas que temos até tarde da noite.' },
  { id: '24', text: 'Porque até o silêncio ao seu lado é confortável.' },
  { id: '25', text: 'A forma como você se lembra dos pequenos detalhes sobre mim.' },
  { id: '26', text: 'Porque, com você, a vida é uma aventura muito mais bonita.' },
  { id: '27', text: 'Sua criatividade e o jeito único que você tem de expressá-la.' },
  { id: '28', text: 'A maneira como você me incentiva a sair da minha zona de conforto.' },
  { id: '29', text: 'O cheiro do seu cabelo.' },
  { id: '30', text: 'O jeito como você fica linda(o) até quando acaba de acordar.' },
  { id: '31', text: 'Sua honestidade, mesmo quando é difícil.' },
  { id: '32', text: 'A forma como você se dedica à sua família e amigos.' },
  { id: '33', text: 'O seu otimismo contagiante.' },
  { id: '34', text: 'Como você prepara meu prato favorito.' },
  { id: '35', text: 'As maratonas de séries que fazemos juntos.' },
  { id: '36', text: 'O seu bom coração.' },
  { id: '37', text: 'A forma como você me desafia a ser mais inteligente.' },
  { id: '38', text: 'Porque você é minha melhor amiga(o) e meu amor.' },
  { id: '39', text: 'O seu estilo e como você sempre se veste bem.' },
  { id: '40', text: 'Como você me ensina coisas novas todos os dias.' },
  { id: '41', text: 'Sua determinação para alcançar seus objetivos.' },
  { id: '42', text: 'O jeito como você dança, mesmo que desajeitadamente.' },
  { id: '43', text: 'A sua voz calma que me tranquiliza.' },
  { id: '44', text: 'Porque você me aceita exatamente como eu sou.' },
  { id: '45', text: 'A forma como você cuida das plantas/animais.' },
  { id: '46', text: 'Seu talento para fazer sobremesas deliciosas.' },
  { id: '47', text: 'A sensação de sua mão na minha.' },
  { id: '48', text: 'A forma como você se emociona com filmes.' },
  { id: '49', text: 'Sua generosidade e vontade de ajudar os outros.' },
  { id: '50', text: 'O jeito como você canta no chuveiro.' },
  { id: '51', text: 'Porque você torna minha vida mais colorida.' },
  { id: '52', text: 'Sua coragem de admitir quando está errada(o).' },
  { id: '53', text: 'A maneira como você se esforça para me fazer feliz.' },
  { id: '54', text: 'O seu cafuné, que é o melhor do mundo.' },
  { id: '55', text: 'Porque você é a primeira pessoa para quem quero contar as novidades.' },
  { id: '56', text: 'A sua energia positiva.' },
  { id: '57', text: 'O seu olhar que diz tudo sem precisar de palavras.' },
  { id: '58', text: 'A forma como você me defende e me protege.' },
  { id: '59', text: 'O jeito como você organiza as coisas.' },
  { id: '60', text: 'Porque aprendemos e crescemos juntos.' },
  { id: '61', text: 'Sua capacidade de perdoar.' },
  { id: '62', text: 'O seu senso de humor peculiar.' },
  { id: '63', text: 'A forma como você lida com o estresse.' },
  { id: '64', text: 'Porque você me faz sentir em casa, não importa onde estejamos.' },
  { id: '65', text: 'Sua habilidade de encontrar beleza nas coisas simples.' },
  { id: '66', text: 'O jeito como você me surpreende com pequenos gestos.' },
  { id: '67', text: 'Sua paixão por seus hobbies.' },
  { id: '68', text: 'A forma como nosso futuro juntos me parece brilhante.' },
  { id: '69', text: 'Porque você sabe ouvir de verdade.' },
  { id: '70', text: 'O seu beijo de bom dia.' },
  { id: '71', text: 'Sua habilidade de me acalmar quando estou ansioso(a).' },
  { id: '72', text: 'O jeito como você fica animado(a) com pequenas coisas.' },
  { id: '73', text: 'Porque você é a peça que faltava no meu quebra-cabeça.' },
  { id: '74', text: 'Sua perspectiva única sobre a vida.' },
  { id: '75', text: 'A forma como você me faz sentir valorizado(a).' },
  { id: '76', text: 'O seu toque suave.' },
  { id: '77', text: 'A maneira como você celebra minhas vitórias como se fossem suas.' },
  { id: '78', text: 'Sua resiliência diante das adversidades.' },
  { id: '79', text: 'Porque você me ensinou o que é o amor verdadeiro.' },
  { id: '80', text: 'O jeito como você se dá bem com a minha família.' },
  { id: '81', 'text': 'A sua curiosidade infinita.' },
  { id: '82', text: 'Porque você me faz querer ser uma versão melhor de mim mesmo.' },
  { id: '83', text: 'A forma como você se lembra de datas importantes.' },
  { id: '84', text: 'O seu cheiro que fica na minha roupa.' },
  { id: '85', text: 'Sua paixão por viajar e conhecer o mundo.' },
  { id: '86', text: 'A maneira como você me dá espaço quando eu preciso.' },
  { id: '87', text: 'O som do seu coração batendo perto do meu.' },
  { id: '88', text: 'Porque você ri das minhas piadas, mesmo quando não têm graça.' },
  { id: '89', text: 'A sua ética de trabalho e dedicação.' },
  { id: '90', text: 'O jeito como você cuida de mim quando estou doente.' },
  { id: '91', text: 'Porque você é meu parceiro(a) em todos os sentidos.' },
  { id: '92', text: 'Sua alma gentil.' },
  { id: '93', text: 'A forma como você me olha, como se eu fosse a única pessoa no mundo.' },
  { id: '94', text: 'Sua capacidade de me fazer sentir seguro para ser vulnerável.' },
  { id: '95', text: 'As nossas piadas internas que só nós entendemos.' },
  { id: '96', text: 'O seu apoio incondicional em todas as minhas decisões.' },
  { id: '97', text: 'A forma como você me ama de volta.' },
  { id: '98', text: 'Porque você torna cada dia uma aventura emocionante.' },
  { id: '99', text: 'O fato de que, depois de todo esse tempo, eu ainda descubro coisas novas para amar em você.' },
  { id: '100', text: 'Simplesmente porque você é você, e isso é mais do que suficiente.' },
  { id: "101", text: "A maneira como você se preocupa com o futuro e faz planos." },
  { id: "102", text: "Sua habilidade de transformar um dia ruim em um dia bom." },
  { id: "103", text: "O jeito que você se aninha em mim quando assistimos a um filme." },
  { id: "104", text: "Porque você é a minha pessoa favorita para não fazer nada junto." },
  { id: "105", text: "A sua determinação em aprender e crescer." },
  { id: "106", text: "Como você fica linda(o) com a luz do sol batendo no seu rosto." },
  { id: "107", text: "O fato de que você me conhece melhor do que eu mesmo." },
  { id: "108", text: "Sua paixão pela arte e pela beleza." },
  { id: "109", text: "A maneira como você me encoraja a cuidar de mim mesmo." },
  { id: "110", text: "O som da sua respiração tranquila quando você dorme." },
  { id: "111", text: "Porque você torna meu mundo um lugar mais seguro." },
  { id: "112", text: "A forma como você celebra as pequenas vitórias da vida." },
  { id: "113", text: "Sua incrível capacidade de ouvir sem julgar." },
  { id: "114", text: "O jeito que você me inspira a ser mais criativo." },
  { id: "115", text: "Porque eu amo as histórias da sua infância." },
  { id: "116", text: "A maneira como você cuida das suas amizades." },
  { id: "117", text: "Sua risada contagiante que ecoa na minha mente." },
  { id: "118", text: "O fato de você sempre ter tempo para mim." },
  { id: "119", text: "Sua habilidade de me fazer sentir a pessoa mais importante do mundo." },
  { id: "120", text: "Como você é atencioso(a) com os detalhes." },
  { id: "121", text: "A forma como você me desafia a pensar de maneira diferente." },
  { id: "122", text: "Porque você é meu raio de sol em dias nublados." },
  { id: "123", text: "Sua generosidade com seu tempo e seu coração." },
  { id: "124", text: "O jeito que você se emociona com músicas." },
  { id: "125", text: "A maneira como você me dá força quando eu me sinto fraco." },
  { id: "126", text: "Porque você é a aventura que eu sempre quis." },
  { id: "127", text: "Sua mente brilhante e suas ideias fascinantes." },
  { id: "128", text: "O jeito como você me olha com orgulho." },
  { id: "129", text: "Porque ao seu lado, eu sou a minha melhor versão." },
  { id: "130", text: "A sua calma em meio ao caos." },
  { id: "131", text: "A maneira como você me ensinou a amar incondicionalmente." },
  { id: "132", text: "O fato de você me fazer sentir borboletas no estômago." },
  { id: "133", text: "Sua paixão por ler e descobrir novos mundos." },
  { id: "134", text: "Como você se esforça para entender meus sentimentos." },
  { id: "135", text: "O jeito que você fica concentrado(a) em algo que ama." },
  { id: "136", text: "Porque cada dia com você é uma nova descoberta." },
  { id: "137", text: "Sua fé em mim, mesmo quando eu duvido." },
  { id: "138", text: "A maneira como você torna a rotina especial." },
  { id: "139", text: "Seu abraço de urso que cura tudo." },
  { id: "140", text: "Porque você é a resposta para todas as minhas preces." },
  { id: "141", text: "Sua habilidade de me fazer sorrir com uma simples mensagem." },
  { id: "142", text: "O jeito como você me inspira a ser mais gentil." },
  { id: "143", text: "A maneira como você me completa." },
  { id: "144", text: "Porque você é meu porto seguro." },
  { id: "145", text: "Sua capacidade de me surpreender todos os dias." },
  { id: "146", text: "O fato de que eu posso ser totalmente eu mesmo com você." },
  { id: "147", text: "Sua voz suave sussurrando no meu ouvido." },
  { id: "148", text: "Como você é apaixonado(a) pela vida." },
  { id: "149", text: "O jeito que você me faz sentir em paz." },
  { id: "150", text: "Porque você é a melhor parte do meu dia." },
  { id: "151", text: "A forma como você se importa com o mundo." },
  { id: "152", text: "Sua beleza interior que irradia para o exterior." },
  { id: "153", text: "O jeito que você me faz sentir corajoso(a)." },
  { id: "154", text: "Porque você é meu sonho realizado." },
  { id: "155", text: "A maneira como você me faz sentir amado(a) e desejado(a)." },
  { id: "156", text: "Sua incrível habilidade de cozinhar." },
  { id: "157", text: "O fato de você sempre saber o que dizer." },
  { id: "158", text: "Como você ilumina qualquer ambiente em que entra." },
  { id: "159", text: "O jeito que você me faz sentir que tudo é possível." },
  { id: "160", text: "Porque nosso amor é minha maior inspiração." },
  { id: "161", text: "Sua elegância natural." },
  { id: "162", text: "A maneira como você me faz sentir especial em meio a multidão." },
  { id: "163", text: "Porque você me ensinou a importância da vulnerabilidade." },
  { id: "164", text: "O jeito como você lida com os desafios com graça." },
  { id: "165", text: "Sua paixão por ajudar os outros." },
  { id: "166", text: "Porque você é a minha pessoa, para sempre." },
  { id: "167", text: "A forma como você me faz sentir completo(a)." },
  { id: "168", text: "O brilho nos seus olhos quando me vê." },
  { id: "169", text: "Sua capacidade de me fazer sentir o centro do universo." },
  { id: "170", text: "Porque você é a melodia da minha vida." },
  { id: "171", text: "O jeito que você me inspira a ser mais saudável." },
  { id: "172", text: "A maneira como você me faz sentir seguro(a) em seus braços." },
  { id: "173", text: "Sua sabedoria e conselhos valiosos." },
  { id: "174", text: "Porque você é a razão do meu sorriso constante." },
  { id: "175", text: "O fato de que você é meu maior fã." },
  { id: "176", text: "Sua incrível capacidade de me fazer sentir em casa." },
  { id: "177", text: "Como você se lembra de pequenas coisas que eu disse." },
  { id: "178", text: "O jeito que você me olha quando pensa que eu não estou vendo." },
  { id: "179", text: "Porque você é a pessoa mais incrível que eu já conheci." },
  { id: "180", text: "A maneira como você me faz sentir que sou suficiente." },
  { id: "181", text: "Sua paixão por animais." },
  { id: "182", text: "O jeito que você me faz sentir o homem/mulher mais sortudo(a) do mundo." },
  { id: "183", text: "Porque você é a minha aventura favorita." },
  { id: "184", text: "A forma como você me ensinou a importância do perdão." },
  { id: "185", text: "Sua habilidade de me fazer rir nos momentos mais inusitados." },
  { id: "186", text: "O jeito que você me faz sentir que posso conquistar o mundo." },
  { id: "187", text: "Porque você é a minha calmaria na tempestade." },
  { id: "188", text: "A maneira como você me inspira a ser mais organizado(a)." },
  { id: "189", text: "Sua gentileza com estranhos." },
  { id: "190", text: "O fato de que você é a pessoa que eu quero ao meu lado para sempre." },
  { id: "191", text: "Como você me faz sentir vivo(a)." },
  { id: "192", text: "O jeito que você me faz sentir amado(a) por quem eu sou." },
  { id: "193", text: "Porque você é a minha paz." },
  { id: "194", text: "A forma como você me ensinou a ser mais paciente." },
  { id: "195", text: "Sua incrível capacidade de me surpreender com gestos de amor." },
  { id: "196", text: "O jeito que você me faz sentir o único(a) no mundo." },
  { id: "197", text: "Porque você é a minha estrela guia." },
  { id: "198", text: "A maneira como você me inspira a ser mais grato(a)." },
  { id: "199", text: "Sua paixão por música e dança." },
  { id: "200", text: "O fato de que você é o meu maior tesouro." },
  { id: "201", text: "Como você me faz sentir que sou parte de algo maior." },
  { id: "202", text: "O jeito que você me faz sentir em um conto de fadas." },
  { id: "203", text: "Porque você é a minha alma gêmea." },
  { id: "204", text: "A forma como você me ensinou a importância de sonhar." },
  { id: "205", text: "Sua incrível capacidade de me fazer sentir amado(a) todos os dias." },
  { id: "206", text: "O jeito que você me faz sentir que sou o seu mundo." },
  { id: "207", text: "Porque você é a minha felicidade." },
  { id: "208", text: "A maneira como você me inspira a ser mais positivo(a)." },
  { id: "209", text: "Sua paixão por fotografia." },
  { id: "210", text: "O fato de que você é o meu amor verdadeiro." },
  { id: "211", text: "Como você me faz sentir que sou a pessoa mais especial do mundo." },
  { id: "212", text: "O jeito que você me faz sentir que sou o seu porto seguro." },
  { id: "213", text: "Porque você é a minha inspiração diária." },
  { id: "214", text: "A forma como você me ensinou a importância da comunicação." },
  { id: "215", text: "Sua incrível capacidade de me fazer sentir amado(a) mesmo à distância." },
  { id: "216", text: "O jeito que você me faz sentir que sou o seu maior presente." },
  { id: "217", text: "Porque você é a minha vida." },
  { id: "218", text: "A maneira como você me inspira a ser mais corajoso(a) para seguir meus sonhos." },
  { id: "219", text: "Sua paixão por jardinagem." },
  { id: "220", text: "O fato de que você é o meu anjo da guarda." },
  { id: "221", text: "Como você me faz sentir que sou a pessoa mais feliz do mundo." },
  { id: "222", text: "O jeito que você me faz sentir que sou o seu amor eterno." },
  { id: "223", text: "Porque você é a minha razão de viver." },
  { id: "224", text: "A forma como você me ensinou a importância de ser feliz." },
  { id: "225", text: "Sua incrível capacidade de me fazer sentir amado(a) em todos os momentos." },
  { id: "226", text: "O jeito que você me faz sentir que sou o seu universo." },
  { id: "227", text: "Porque você é o meu tudo." },
  { id: "228", text: "A maneira como você me inspira a ser uma pessoa mais amorosa." },
  { id: "229", text: "Sua paixão por voluntariado." },
  { id: "230", text: "O fato de que você é o meu milagre." },
  { id: "231", text: "Como você me faz sentir que sou a pessoa mais amada do universo." },
  { id: "232", text: "O jeito que você me faz sentir que sou o seu maior amor." },
  { id: "233", text: "Porque você é a minha eternidade." },
  { id: "234", text: "A forma como você me ensinou a importância do amor próprio." },
  { id: "235", text: "Sua incrível capacidade de me fazer sentir amado(a) a cada segundo." },
  { id: "236", text: "O jeito que você me faz sentir que sou o seu sol." },
  { id: "237", text: "Porque você é a minha luz." },
  { id: "238", text: "A maneira como você me inspira a ser mais feliz." },
  { id: "239", text: "Sua paixão por esportes radicais." },
  { id: "240", text: "O fato de que você é o meu destino." },
  { id: "241", text: "Como você me faz sentir que sou a pessoa mais sortuda do mundo por ter você." },
  { id: "242", text: "O jeito que você me faz sentir que sou o seu amor para toda a vida." },
  { id: "243", text: "Porque você é a minha alma." },
  { id: "244", text: "A forma como você me ensinou a importância de viver o presente." },
  { id: "245", text: "Sua incrível capacidade de me fazer sentir amado(a) em cada gesto." },
  { id: "246", text: "O jeito que você me faz sentir que sou o seu anjo." },
  { id: "247", text: "Porque você é o meu paraíso." },
  { id: "248", text: "A maneira como você me inspira a ser uma pessoa melhor para você." },
  { id: "249", text: "Sua paixão por culinária exótica." },
  { id: "250", text: "O fato de que você é o meu sonho tornado realidade." },
  { id: "251", text: "A maneira como você me faz sentir seguro e protegido." },
  { id: "252", text: "O seu senso de humor que sempre me faz rir." },
  { id: "253", text: "A forma como você me apoia incondicionalmente." },
  { id: "254", text: "O seu otimismo contagiante." },
  { id: "255", text: "A maneira como você me faz sentir em casa." },
  { id: "256", text: "A sua paixão por aprender coisas novas." },
  { id: "257", text: "O seu jeito de me olhar com admiração." },
  { id: "258", text: "A sua lealdade inabalável." },
  { id: "259", text: "O seu toque gentil e carinhoso." },
  { id: "260", text: "A maneira como você me inspira a ser mais corajoso." },
  { id: "261", text: "A sua voz calma e tranquilizadora." },
  { id: "262", text: "O seu jeito de me fazer sentir especial." },
  { id: "263", text: "A sua paciência infinita comigo." },
  { id: "264", text: "A sua capacidade de me perdoar." },
  { id: "265", text: "A sua forma de me amar por quem eu sou." },
  { id: "266", text: "O seu jeito de me fazer sorrir sem motivo." },
  { id: "267", text: "A sua inteligência e sabedoria." },
  { id: "268", text: "A sua bondade com todos ao seu redor." },
  { id: "269", text: "A sua força interior e resiliência." },
  { id: "270", text: "O seu jeito de me fazer sentir o homem mais feliz do mundo." },
  { id: "271", text: "A sua criatividade e imaginação." },
  { id: "272", text: "A sua paixão pela vida." },
  { id: "273", text: "O seu jeito de me fazer sentir amado e valorizado." },
  { id: "274", text: "A sua forma de me ensinar a ser uma pessoa melhor." },
  { id: "275", text: "O seu jeito de me fazer sentir completo." },
  { id: "276", text: "A sua beleza que vai além da aparência." },
  { id: "277", text: "A sua dedicação em tudo o que faz." },
  { id: "278", text: "O seu jeito de me fazer sentir o único." },
  { id: "279", text: "A sua forma de me fazer acreditar em mim mesmo." },
  { id: "280", text: "O seu jeito de me fazer sentir que tudo vai ficar bem." },
  { id: "281", text: "A sua risada que é a minha música favorita." },
  { id: "282", text: "O seu abraço que é o meu refúgio." },
  { id: "283", text: "O seu cheiro que me acalma." },
  { id: "284", text: "O seu olhar que me diz tudo." },
  { id: "285", text: "O seu beijo que me transporta para outro mundo." },
  { id: "286", text: "A sua presença que ilumina o meu dia." },
  { id: "287", text: "O seu amor que me completa." },
  { id: "288", text: "A sua existência que torna a minha vida melhor." },
  { id: "289", text: "O seu sorriso tímido." },
  { id: "290", text: "A forma como você se preocupa com os animais." },
  { id: "291", text: "As caretas que você faz quando está concentrada." },
  { id: "292", text: "O seu gosto para filmes e séries." },
  { id: "293", text: "A maneira como você me ensina a ser mais organizado." },
  { id: "294", text: "O seu jeito de dançar pela casa." },
  { id: "295", text: "A sua habilidade de fazer amigos em qualquer lugar." },
  { id: "296", text: "O seu amor por dias chuvosos e cobertores." },
  { id: "297", text: "A sua forma de me surpreender com pequenos presentes." },
  { id: "298", text: "O seu apoio nos meus hobbies mais estranhos." },
  { id: "299", text: "A sua empolgação com datas comemorativas." },
  { id: "300", text: "O seu jeito de me fazer sentir jovem para sempre." },
  { id: "301", text: "A sua capacidade de me fazer sentir saudades, mesmo estando perto." },
  { id: "302", text: "O seu respeito pelas minhas opiniões." },
  { id: "303", text: "A sua coragem de enfrentar seus medos." },
  { id: "304", text: "O seu amor por experimentar comidas diferentes." },
  { id: "305", text: "A sua forma de me fazer rir de mim mesmo." },
  { id: "306", text: "O seu jeito de cuidar das plantas." },
  { id: "307", text: "A sua paixão por viajar e conhecer novas culturas." },
  { id: "308", text: "A sua forma de me incentivar a ser mais saudável." },
  { id: "309", text: "O seu jeito de me fazer sentir o homem mais forte do mundo." },
  { id: "310", text: "A sua capacidade de me fazer sentir paz interior." },
  { id: "311", text: "O seu amor por longas caminhadas." },
  { id: "312", text: "A sua forma de me fazer sentir que sou o seu herói." },
  { id: "313", text: "O seu jeito de me fazer sentir que sou o seu príncipe." },
  { id: "314", text: "A sua forma de me fazer sentir que sou o seu rei." },
  { id: "315", text: "O seu jeito de me fazer sentir que sou o seu tudo." },
  { id: "316", text: "A sua capacidade de me fazer sentir o homem mais amado do mundo." },
  { id: "317", text: "O seu amor por noites estreladas." },
  { id: "318", text: "A sua forma de me fazer sentir que sou o seu porto seguro." },
  { id: "319", text: "O seu jeito de me fazer sentir que sou o seu melhor amigo." },
  { id: "320", text: "A sua capacidade de me fazer sentir o homem mais sortudo do mundo." },
  { id: "321", text: "O seu amor por conversas profundas." },
  { id: "322", text: "A sua forma de me fazer sentir que sou o seu parceiro para a vida." },
  { id: "323", text: "O seu jeito de me fazer sentir que sou o seu cúmplice." },
  { id: "324", text: "A sua capacidade de me fazer sentir o homem mais realizado do mundo." },
  { id: "325", text: "O seu amor por desafios." },
  { id: "326", text: "A sua forma de me fazer sentir que sou o seu maior fã." },
  { id: "327", text: "O seu jeito de me fazer sentir que sou o seu maior orgulho." },
  { id: "328", text: "A sua capacidade de me fazer sentir o homem mais completo do mundo." },
  { id: "329", text: "O seu amor por manhãs preguiçosas." },
  { id: "330", text: "A sua forma de me fazer sentir que sou o seu amor eterno." },
  { id: "331", text: "O seu jeito de me fazer sentir que sou o seu companheiro de aventuras." },
  { id: "332", text: "A sua capacidade de me fazer sentir o homem mais feliz da Terra." },
  { id: "333", text: "O seu amor por piqueniques no parque." },
  { id: "334", text: "A sua forma de me fazer sentir que sou o seu confidente." },
  { id: "335", text: "O seu jeito de me fazer sentir que sou o seu amor para sempre." },
  { id: "336", text: "A sua capacidade de me fazer sentir o homem mais especial do mundo." },
  { id: "337", text: "O seu amor por pores do sol." },
  { id: "338", text: "A sua forma de me fazer sentir que sou o seu protetor." },
  { id: "339", text: "O seu jeito de me fazer sentir que sou o seu amor da sua vida." },
  { id: "340", text: "A sua capacidade de me fazer sentir o homem mais amado da galáxia." },
  { id: "341", text: "O seu amor por noites de jogos." },
  { id: "342", text: "A sua forma de me fazer sentir que sou o seu noivo." },
  { id: "343", text: "O seu jeito de me fazer sentir que sou o seu marido." },
  { id: "344", text: "A sua capacidade de me fazer sentir o homem mais abençoado do mundo." },
  { id: "345", text: "O seu amor por surpresas românticas." },
  { id: "346", text: "A sua forma de me fazer sentir que sou o seu amor de verdade." },
  { id: "347", text: "O seu jeito de me fazer sentir que sou o seu príncipe encantado." },
  { id: "348", text: "A sua capacidade de me fazer sentir o homem mais amado do universo." },
  { id: "349", text: "O seu amor por dançar na chuva." },
  { id: "350", text: "A sua forma de me fazer sentir que sou o seu amor perfeito." },
  { id: "351", text: "O seu jeito de me fazer sentir que sou o seu amor infinito." },
  { id: "352", text: "A sua capacidade de me fazer sentir o homem mais sortudo da história." },
  { id: "353", text: "O seu amor por escrever cartas de amor." },
  { id: "354", text: "A sua forma de me fazer sentir que sou o seu amor incondicional." },
  { id: "355", text: "O seu jeito de me fazer sentir que sou o seu amor único." },
  { id: "356", text: "A sua capacidade de me fazer sentir o homem mais amado por você." },
  { id: "357", text: "O seu amor por fazer planos para o nosso futuro." },
  { id: "358", text: "A sua forma de me fazer sentir que sou o seu amor eterno e verdadeiro." },
  { id: "359", text: "O seu jeito de me fazer sentir que sou o seu amor para toda a eternidade." },
  { id: "360", text: "A sua capacidade de me fazer sentir o homem mais amado deste e de outros mundos." },
  { id: "361", text: "O seu amor por construir uma vida juntos." },
  { id: "362", text: "A sua forma de me fazer sentir que sou o seu amor para sempre e um dia." },
  { id: "363", text: "O seu jeito de me fazer sentir que nosso amor é uma obra de arte." },
  { id: "364", text: "A sua capacidade de me amar mais a cada dia." },
  { id: "365", text: "Porque, de todas as razões, a maior é simplesmente amar você." },
];

export const INITIAL_QUOTES: LoveQuote[] = [
  { id: '1', text: 'Amar não é olhar um para o outro, é olhar juntos na mesma direção.', author: 'Antoine de Saint-Exupéry' },
  { id: '2', text: 'O amor é a amizade que pegou fogo.', author: 'Ann Landers' },
  { id: '3', text: 'Sei que vou te amar por toda a minha vida.', author: 'Vinicius de Moraes' },
  { id: '4', text: 'Te amo não pelo que você é, mas pelo que sou quando estou com você.', author: 'Roy Croft' },
  { id: '5', text: 'Onde há amor, há vida.', author: 'Mahatma Gandhi' },
];

export const INITIAL_AFFECTION_MESSAGES: string[] = [
  "Você ilumina meu dia!",
  "Pensando em você ❤️",
  "Você é incrível!",
  "Um abraço virtual apertado!",
  "Mal posso esperar para te ver!",
  "Você me faz sorrir 😊",
  "Lembre-se: você é especial!",
  "Com carinho, para você.",
  "Cada momento ao seu lado é um presente.",
  "Você é meu pensamento favorito.",
  "Que seu dia seja tão lindo quanto você!",
  "Sua felicidade é a minha."
];
