
import type { Memory, Photo, Reason, LoveQuote } from './types';

// The 'T00:00:00' part is important to avoid timezone issues and ensure the date is consistent.
export const START_DATING_DATE = new Date('2025-08-02T00:00:00');

export const INITIAL_MEMORIES: Memory[] = [
  {
    id: '1',
    date: new Date('2025-08-02T00:00:00'),
    title: 'Nossa Jornada Começou',
    description: 'O lindo dia em que oficialmente começamos a namorar e nossos corações se entrelaçaram.',
    tags: ['aniversário', 'amor'],
    image: 'https://i.pinimg.com/736x/81/71/51/8171515f162cc1254da32d59c23ad43f.jpg',
    dataAiHint: 'casal feliz',
  },
  {
    id: '2',
    date: new Date('2025-08-10T00:00:00'),
    title: 'Primeiro Encontro no Cinema',
    description: 'Assistimos aquela comédia romântica e não parávamos de rir. Lembra do incidente da pipoca?',
    tags: ['encontro', 'diversão'],
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'cinema casal',
  },
  {
    id: '3',
    date: new Date('2025-09-22T00:00:00'),
    title: 'Felicidade na Praia',
    description: 'Nossa primeira viagem à praia juntos. O pôr do sol era quase tão lindo quanto você.',
    tags: ['viagem', 'natureza'],
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'praia por do sol',
  },
   {
    id: '4',
    date: new Date('2025-10-15T00:00:00'),
    title: 'Passeio de Outono',
    description: 'Um dia tranquilo aproveitando o ar fresco e as cores do outono, sempre juntos.',
    tags: ['passeio', 'natureza'],
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'casal outono',
  },
  {
    id: '5',
    date: new Date('2025-11-05T00:00:00'),
    title: 'Abraço Aconchegante',
    description: 'Não há lugar no mundo onde eu me sinta mais seguro e amado do que em seus braços.',
    tags: ['carinho', 'amor'],
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'casal abraço',
  },
  {
    id: '6',
    date: new Date('2025-12-25T00:00:00'),
    title: 'Nosso Primeiro Natal',
    description: 'Celebrando o Natal juntos, criando nossas próprias tradições e memórias.',
    tags: ['celebração', 'feriado'],
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'casal natal',
  },
  {
    id: '7',
    date: new Date('2026-01-01T00:00:00'),
    title: 'Votos de Ano Novo',
    description: 'Brindando a um novo ano de amor, aventuras e felicidade um ao lado do outro.',
    tags: ['celebração', 'futuro'],
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'casal ano novo',
  },
];

export const INITIAL_PHOTOS: Photo[] = [
  {
    id: '1',
    src: 'https://placehold.co/521x927.png',
    alt: 'Um lindo abraço carinhoso',
    caption: 'Em seus braços, encontro meu porto seguro e todo o amor do mundo. ❤️',
    date: new Date('2025-11-05T00:00:00'),
    dataAiHint: 'casal abraço'
  },
  {
    id: '2',
    src: 'https://placehold.co/1647x927.png',
    alt: 'Celebrando um momento especial',
    caption: 'Cada momento com você se torna uma celebração da nossa felicidade.',
    date: new Date('2025-12-25T00:00:00'),
    dataAiHint: 'casal celebração'
  },
  {
    id: '3',
    src: 'https://placehold.co/1647x927.png',
    alt: 'Olhando para o futuro juntos',
    caption: 'Juntos, de mãos dadas, prontos para todos os lindos capítulos que ainda vamos escrever.',
    date: new Date('2026-01-01T00:00:00'),
    dataAiHint: 'casal futuro'
  },
  {
    id: '4',
    src: 'https://placehold.co/522x927.png',
    alt: 'Passeio tranquilo e romântico',
    caption: 'A simplicidade de um passeio se torna extraordinária quando estou com você.',
    date: new Date('2025-10-15T00:00:00'),
    dataAiHint: 'casal passeio'
  },
  {
    id: '5',
    src: 'https://placehold.co/522x927.png',
    alt: 'Explorando uma nova cidade',
    caption: 'Nossa aventura de fim de semana.',
    date: new Date('2025-11-18T00:00:00'),
    dataAiHint: 'casal viagem'
  },
];

export const INITIAL_REASONS: Reason[] = [
  { id: '1', text: 'Seu lindo sorriso que ilumina meu mundo inteiro todos os dias.' },
  { id: '2', text: 'Sua bondade e compaixão inabaláveis por todos que você conhece.' },
  { id: '3', text: 'A maneira como você me faz rir até a barriga doer, mesmo nos dias difíceis.' },
  { id: '4', text: 'Sua inteligência incrível e a forma como você vê o mundo.' },
  { id: '5', text: 'O quanto você apoia meus sonhos e ambições.' },
  { id: '6', text: 'Seu espírito aventureiro e disposição para experimentar coisas novas comigo.' },
  { id: '7', text: 'A forma como você sempre sabe como me confortar quando estou para baixo.' },
  { id: '8', text: 'Seu abraço, que é o meu lugar favorito no mundo.' },
  { id: '9', text: 'A paciência infinita que você tem comigo.' },
  { id: '10', text: 'O jeito que seus olhos brilham quando você fala sobre algo que ama.' },
  { id: '11', text: 'Você me inspira a ser uma pessoa melhor a cada dia.' },
  { id: '12', text: 'Sua lealdade e a certeza de que posso contar com você para tudo.' },
  { id: '13', text: 'A forma como transformamos momentos simples em memórias inesquecíveis.' },
  { id: '14', text: 'Sua força para enfrentar qualquer desafio que a vida apresenta.' },
  { id: '15', text: 'O som da sua risada é a minha melodia favorita.' },
  { id: '16', text: 'Porque você me entende com apenas um olhar.' },
  { id: '17', text: 'A maneira como você cuida de mim e se preocupa com meu bem-estar.' },
  { id: '18', text: 'Seu gosto musical incrível, que me apresentou tantas músicas novas.' },
  { id: '19', text: 'Você me faz sentir a pessoa mais amada e especial do universo.' },
  { id: '20', text: 'A segurança que sinto ao segurar sua mão.' },
  { id: '21', text: 'Sua paixão pela vida e por aprender coisas novas.' },
  { id: '22', text: 'Como você consegue ser a pessoa mais fofa e a mais forte ao mesmo tempo.' },
  { id: '23', text: 'As conversas profundas que temos até tarde da noite.' },
  { id: '24', text: 'Porque até o silêncio ao seu lado é confortável.' },
  { id: '25', text: 'A forma como você se lembra dos pequenos detalhes sobre mim.' },
  { id: '26', text: 'Porque, com você, a vida é uma aventura muito mais bonita.' },
  { id: '27', text: 'Sua criatividade e o jeito único que você tem de expressá-la.' },
  { id: '28', text: 'A maneira como você me incentiva a sair da minha zona de conforto.' },
  { id: '29', text: 'O cheiro do seu cabelo.' },
  { id: '30', text: 'O jeito como você fica linda(o) até quando acaba de acordar.' },
  { id: '31', text: 'Sua honestidade, mesmo quando é difícil.' },
  { id: '32', text: 'A forma como você se dedica à sua família e amigos.' },
  { id: '33', text: 'O seu otimismo contagiante.' },
  { id: '34', text: 'Como você prepara meu prato favorito.' },
  { id: '35', text: 'As maratonas de séries que fazemos juntos.' },
  { id: '36', text: 'O seu bom coração.' },
  { id: '37', text: 'A forma como você me desafia a ser mais inteligente.' },
  { id: '38', text: 'Porque você é minha melhor amiga(o) e meu amor.' },
  { id: '39', text: 'O seu estilo e como você sempre se veste bem.' },
  { id: '40', text: 'Como você me ensina coisas novas todos os dias.' },
  { id: '41', text: 'Sua determinação para alcançar seus objetivos.' },
  { id: '42', text: 'O jeito como você dança, mesmo que desajeitadamente.' },
  { id: '43', text: 'A sua voz calma que me tranquiliza.' },
  { id: '44', text: 'Porque você me aceita exatamente como eu sou.' },
  { id: '45', text: 'A forma como você cuida das plantas/animais.' },
  { id: '46', text: 'Seu talento para fazer sobremesas deliciosas.' },
  { id: '47', text: 'A sensação de sua mão na minha.' },
  { id: '48', text: 'A forma como você se emociona com filmes.' },
  { id: '49', text: 'Sua generosidade e vontade de ajudar os outros.' },
  { id: '50', text: 'O jeito como você canta no chuveiro.' },
  { id: '51', text: 'Porque você torna minha vida mais colorida.' },
  { id: '52', text: 'Sua coragem de admitir quando está errada(o).' },
  { id: '53', text: 'A maneira como você se esforça para me fazer feliz.' },
  { id: '54', text: 'O seu cafuné, que é o melhor do mundo.' },
  { id: '55', text: 'Porque você é a primeira pessoa para quem quero contar as novidades.' },
  { id: '56', text: 'A sua energia positiva.' },
  { id: '57', text: 'O seu olhar que diz tudo sem precisar de palavras.' },
  { id: '58', text: 'A forma como você me defende e me protege.' },
  { id: '59', text: 'O jeito como você organiza as coisas.' },
  { id: '60', text: 'Porque aprendemos e crescemos juntos.' },
  { id: '61', text: 'Sua capacidade de perdoar.' },
  { id: '62', text: 'O seu senso de humor peculiar.' },
  { id: '63', text: 'A forma como você lida com o estresse.' },
  { id: '64', text: 'Porque você me faz sentir em casa, não importa onde estejamos.' },
  { id: '65', text: 'Sua habilidade de encontrar beleza nas coisas simples.' },
  { id: '66', text: 'O jeito como você me surpreende com pequenos gestos.' },
  { id: '67', text: 'Sua paixão por seus hobbies.' },
  { id: '68', text: 'A forma como nosso futuro juntos me parece brilhante.' },
  { id: '69', text: 'Porque você sabe ouvir de verdade.' },
  { id: '70', text: 'O seu beijo de bom dia.' },
  { id: '71', text: 'Sua habilidade de me acalmar quando estou ansioso(a).' },
  { id: '72', text: 'O jeito como você fica animado(a) com pequenas coisas.' },
  { id: '73', text: 'Porque você é a peça que faltava no meu quebra-cabeça.' },
  { id: '74', text: 'Sua perspectiva única sobre a vida.' },
  { id: '75', text: 'A forma como você me faz sentir valorizado(a).' },
  { id: '76', text: 'O seu toque suave.' },
  { id: '77', text: 'A maneira como você celebra minhas vitórias como se fossem suas.' },
  { id: '78', text: 'Sua resiliência diante das adversidades.' },
  { id: '79', text: 'Porque você me ensinou o que é o amor verdadeiro.' },
  { id: '80', text: 'O jeito como você se dá bem com a minha família.' },
  { id: '81', text: 'A sua curiosidade infinita.' },
  { id: '82', text: 'Porque você me faz querer ser uma versão melhor de mim mesmo.' },
  { id: '83', text: 'A forma como você se lembra de datas importantes.' },
  { id: '84', text: 'O seu cheiro que fica na minha roupa.' },
  { id: '85', text: 'Sua paixão por viajar e conhecer o mundo.' },
  { id: '86', text: 'A maneira como você me dá espaço quando eu preciso.' },
  { id: '87', text: 'O som do seu coração batendo perto do meu.' },
  { id: '88', text: 'Porque você ri das minhas piadas, mesmo quando não têm graça.' },
  { id: '89', text: 'A sua ética de trabalho e dedicação.' },
  { id: '90', text: 'O jeito como você cuida de mim quando estou doente.' },
  { id: '91', text: 'Porque você é meu parceiro(a) em todos os sentidos.' },
  { id: '92', text: 'Sua alma gentil.' },
  { id: '93', text: 'A forma como você me olha, como se eu fosse a única pessoa no mundo.' },
  { id: '94', text: 'Sua capacidade de me fazer sentir seguro para ser vulnerável.' },
  { id: '95', text: 'As nossas piadas internas que só nós entendemos.' },
  { id: '96', text: 'O seu apoio incondicional em todas as minhas decisões.' },
  { id: '97', text: 'A forma como você me ama de volta.' },
  { id: '98', text: 'Porque você torna cada dia uma aventura emocionante.' },
  { id: '99', text: 'O fato de que, depois de todo esse tempo, eu ainda descubro coisas novas para amar em você.' },
  { id: '100', text: 'Simplesmente porque você é você, e isso é mais do que suficiente.' },
];

export const INITIAL_QUOTES: LoveQuote[] = [
  { id: '1', text: 'Amar não é olhar um para o outro, é olhar juntos na mesma direção.', author: 'Antoine de Saint-Exupéry' },
  { id: '2', text: 'O amor é a amizade que pegou fogo.', author: 'Ann Landers' },
  { id: '3', text: 'Sei que vou te amar por toda a minha vida.', author: 'Vinicius de Moraes' },
  { id: '4', text: 'Te amo não pelo que você é, mas pelo que sou quando estou com você.', author: 'Roy Croft' },
  { id: '5', text: 'Onde há amor, há vida.', author: 'Mahatma Gandhi' },
];

export const INITIAL_AFFECTION_MESSAGES: string[] = [
  "Você ilumina meu dia!",
  "Pensando em você ❤️",
  "Você é incrível!",
  "Um abraço virtual apertado!",
  "Mal posso esperar para te ver!",
  "Você me faz sorrir 😊",
  "Lembre-se: você é especial!",
  "Com carinho, para você.",
  "Cada momento ao seu lado é um presente.",
  "Você é meu pensamento favorito.",
  "Que seu dia seja tão lindo quanto você!",
  "Sua felicidade é a minha."
];
